
name: multi-stage-deploy

on:
  push:
    branches: 
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build application bundle
        run: npm run build
  stage:
    runs-on: staging
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to staging environment
        uses: some-deployment-action
        with:
          application_bundle: ${{ needs.build.outputs.application_bundle }}
          environment_variables: ${{ secrets.STAGING_ENV_VARS }}
  production-deploy:
    runs-on: production
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to production environment
        uses: some-deployment-action
        with:
          application_bundle: ${{ needs.build.outputs.application_bundle }}
         